CREATE TABLE IF NOT EXISTS "DB002_ACESSO" (
  "001_AcessoAte" text,
  "002_UltimoAcesso" timestamp without time zone,
  "003_EmpresasAcesso" text,
  "004_Recorrencia" text,
  "005_NovosModelos" text,
  "006_Plano" text,
  "007_FiscAtivo" text,
  "008_FiscCNPJ" text,
  "009_FiscIE" text,
  "010_RegimeTrib" text,
  "011_AsaasCusID" text,
  "012_CadastroCompleto" text,
  "013_CNPJ" text,
  "014_ComercialStatus" text,
  "015_EnderecoEmpresa" text,
  "016_InfoPagtoAssinatura" text,
  "017_Instagram" text,
  "018_LimiteUsuarios" text,
  "019_LogoEmpresa" text,
  "020_NomeEmpresa" text,
  "021_PrimeiroAcesso" text,
  "022_QtdVendedores" text,
  "023_TelefoneEmpresa" text,
  "024_TermoEmpresa" text,
  "025_UsuarioAdicional" text,
  "026_Beta" text,
  "027_SuperBeta" text,
  "028_Termos" text,
  "029_IDVisual" text,
  "030_Certificado" text,
  "031_RFFiscal" text,
  "032_AguardandoAprovacao" text,
  "033_EmailEmpresa" text,
  "034_NovasCores" text,
  "035_AddOnAssistencia" text,
  "036_AddOnEmpFiscal" text,
  "037_Carteira" text,
  "038_CRMAcessoAte" text,
  "039_AdicionaDias" text,
  "040_APIKey" text,
  "041_Assinatura" text,
  "042_AssinaturaIrregular" text,
  "043_Engajamento" text,
  "043_FaturaUrl" text,
  "044_PrimeiroPagto" text,
  "045_IDUnicoTXT" text,
  "046_ConfiguracoesGerais" text,
  "047_OSPlanos" text,
  "048_Project" text,
  "049_RegimeTribuario" text,
  "050_Dispositivos" text,
  "051_EngajamentoCount-2025" text,
  "052_EngajamentoCount-2026" text,
  "Creation Date" text,
  "Modified Date" text,
  "Slug" text,
  "Creator" text,
  "unique_id" text NOT NULL,
  "uuid" uuid NOT NULL DEFAULT gen_random_uuid(),
  CONSTRAINT "DB002_ACESSO_pkey" PRIMARY KEY ("unique_id", "uuid")
);

ALTER TABLE "DB002_ACESSO" ENABLE ROW LEVEL SECURITY;
