CREATE TABLE IF NOT EXISTS "DB002_EMPRESAS" (
  "001_AcessoAte" timestamp without time zone,
  "002_UltimoAcesso" timestamp without time zone,
  "003_EmpresasAcesso" text,
  "004_Recorrencia" text,
  "005_NovosModelos" boolean,
  "006_Plano" text,
  "007_FiscAtivo" boolean DEFAULT false,
  "008_FiscCNPJ" text,
  "009_FiscIE" text,
  "010_RegimeTrib" text,
  "011_AsaasCusID" text,
  "012_CadastroCompleto" boolean DEFAULT false,
  "013_CNPJ" text,
  "014_ComercialStatus" text,
  "015_EnderecoEmpresa" text,
  "016_InfoPagtoAssinatura" boolean DEFAULT false,
  "017_Instagram" text,
  "018_LimiteUsuarios" text,
  "019_LogoEmpresa" text,
  "020_NomeEmpresa" text,
  "021_PrimeiroAcesso" boolean DEFAULT true,
  "022_QtdVendedores" text,
  "023_TelefoneEmpresa" text,
  "024_TermoEmpresa" text,
  "025_UsuarioAdicional" text,
  "026_Beta" boolean,
  "027_SuperBeta" boolean,
  "028_Termos" text,
  "029_IDVisual" text,
  "030_Certificado" text,
  "031_RFFiscal" text,
  "032_AguardandoAprovacao" boolean DEFAULT true,
  "033_EmailEmpresa" text,
  "034_NovasCores" boolean,
  "035_AddOnAssistencia" boolean DEFAULT true,
  "036_AddOnEmpFiscal" text,
  "037_Carteira" text,
  "038_CRMAcessoAte" timestamp without time zone,
  "039_AdicionaDias" boolean,
  "040_APIKey" text,
  "041_Assinatura" text,
  "042_AssinaturaIrregular" boolean,
  "043_Engajamento" text,
  "043_FaturaUrl" text,
  "044_PrimeiroPagto" boolean,
  "045_IDUnicoTXT" text,
  "046_ConfiguracoesGerais" text,
  "047_OSPlanos" text,
  "048_Project" text,
  "049_RegimeTribuario" text,
  "050_Dispositivos" text,
  "051_EngajamentoCount-2025" text,
  "052_EngajamentoCount-2026" text,
  "Creation Date" timestamp without time zone,
  "Modified Date" timestamp without time zone,
  "Slug" text,
  "Creator" text,
  "unique_id" text NOT NULL,
  "uuid" uuid DEFAULT gen_random_uuid(),
  CONSTRAINT "DB002_EMPRESAS_pkey" PRIMARY KEY ("unique_id")
);

ALTER TABLE "DB002_EMPRESAS" ENABLE ROW LEVEL SECURITY;
