CREATE TABLE IF NOT EXISTS "DB001_ASSINATURAS" (
  "000_Empresa" text,
  "001_CusID" text,
  "002_AsaasDescricao" text,
  "003_AsaasParcela" text,
  "004_Mensalidade" text,
  "005_Plano" text,
  "006_Recorrencia" text,
  "007_TotalPago" text,
  "008_TicketMedio" text,
  "009_DataCriacaoAssinatura" timestamp with time zone,
  "010_DataAcessoAte" timestamp with time zone,
  "011_Ativo" boolean DEFAULT false,
  "012_Cancelado" boolean DEFAULT false,
  "013_MotivoCancelamento" text,
  "014_TipoMotivoCancelamento" text,
  "015_DataCancelamento" timestamp with time zone,
  "016_NomeAssinante" text,
  "017_CidadeAssinante" text,
  "017_ContatoAssinante" text,
  "018_AssinanteUF" text,
  "019_ObservacoesAdicionais" text,
  "020_FormaEntrada" text,
  "021_AsaasEvento" text,
  "022_AsaasStatus" text,
  "023_AsaasValorRecebido" text,
  "024_CupomAtivado" text,
  "025_DToken" text,
  "Creation Date" timestamp with time zone,
  "Modified Date" timestamp with time zone,
  "Slug" text,
  "Creator" text,
  "unique_id" text NOT NULL,
  CONSTRAINT "DB001_ASSINATURAS_pkey" PRIMARY KEY ("unique_id")
);

ALTER TABLE "DB001_ASSINATURAS" ENABLE ROW LEVEL SECURITY;
