CREATE TABLE IF NOT EXISTS "DB017_COM_COMPRA" (
  "000_Empresa" text,
  "001_ATIVO" boolean,
  "002_CONCRETIZADA" boolean,
  "003_PAGTO_FRETE" text,
  "004_PAGTO_IMPOSTO" text,
  "005_PAGTO_OUTRAS" text,
  "006_Cancelada por" text,
  "007_Data cancelamento" timestamp without time zone,
  "008_Motivo cancelamento" text,
  "009_COD_NOTA" text,
  "010_CPF-CNPJ" text,
  "011_CAIXA" text,
  "012_FORMA" text,
  "013_ProdutosComprados" text,
  "014_DATA_COMPRA" timestamp without time zone,
  "015_FORNECEDOR" text,
  "016_ORIGEM" text,
  "017_PAGTO_DATA" timestamp without time zone,
  "018_PAGTO_DESCONTO" text,
  "019_PAGTO_OCORRENCIA" text,
  "020_PAGTO_QUITADO" text,
  "021_PAGTO_RECORRENCIA" integer,
  "022_QTD_PARCELAS" integer,
  "023_TOTAL_BRUTO" text,
  "024_TOTAL_PRODUTOS" text,
  "025_VALOR_POR_PARCELA" text,
  "026_DOC_FISCAL" boolean,
  "027_ID-CHAVE" text,
  "028_NF_Cod-ENT" text,
  "029_CAP-CAR" text,
  "030_MenuEntradaInfo" text,
  "031_TXT_FORMA_PAGTO" text,
  "032_ID-UNICO" text,
  "Creation Date" timestamp without time zone,
  "Modified Date" timestamp without time zone,
  "Slug" text,
  "Creator" text,
  "unique_id" text NOT NULL,
  CONSTRAINT "DB017_COM_COMPRAS_pkey" PRIMARY KEY ("unique_id")
);

ALTER TABLE "DB017_COM_COMPRA" ENABLE ROW LEVEL SECURITY;
