CREATE TABLE IF NOT EXISTS "DB016_CLI_CLIENTE" (
  "000_Empresa" text,
  "001_ATIVO]" boolean,
  "002_CLIENTE_NOME]" text,
  "003_CPF_CNPJ_Normalizado" text,
  "004_CLIENTE_CPF_OU_CNPJ]" text,
  "005_CLIENTE_EMAIL]" text,
  "006_CLIENTE_TELEFONE_01]" text,
  "007_CLIENTE_DATA_NASCIMENTO]" date,
  "008_CLIENTE_MES_ANIVER]" integer,
  "009_CLIENTE_DIA_ANIVER]" integer,
  "010_CLIENTE_GENERO]" text,
  "011_END_RUA]" text,
  "012_END_COMPLEMENTO]" text,
  "013_END_NUM]" text,
  "014_END_BAIRRO]" text,
  "015_END_CIDADE" text,
  "016_END_CEP]" text,
  "017_END_UF]" text,
  "018_COMO_CONHECEU]" text,
  "019_OUTRA_FORMA]" text,
  "020_POSSUI_EMP]" boolean,
  "021_EMP_ATIVOS]" text,
  "022_DATA_CRIACAO]" text,
  "023_TIPO_CLIENTE]" text,
  "024_INFO_ADICIONAL]" text,
  "025_DDI_NUMERO]" bigint,
  "026_DATA_CORRETA]" timestamp without time zone,
  "027_ETIQUETAS]" text,
  "028_CARTEIRA_USUARIO]" text,
  "029_INSTAGRAM_CLIENTE" text,
  "030_ATENDIMENTOS-VINCULADOS" text,
  "031_TOTAL-ATE" integer,
  "032_ULTIMO-ATE-DATA" timestamp without time zone,
  "033_VINCULADOS" text,
  "034_TOTAL-OS" integer,
  "035_ULTIMA-OS-DATA" timestamp without time zone,
  "036_QTD-CARAC" integer,
  "037_Teste123" integer,
  "038_TXT_GENERO" text,
  "039_ID-UNICO" text,
  "040_Credito em vendas" real,
  "041_Credito Historico de entradas" text,
  "042_Credito Historico de saidas" text,
  "Creation Date" timestamp without time zone,
  "Modified Date" timestamp without time zone,
  "Slug" text,
  "Creator" text,
  "unique_id" text NOT NULL,
  CONSTRAINT "DB016_CLI-CLIENTES_pkey" PRIMARY KEY ("unique_id")
);

ALTER TABLE "DB016_CLI_CLIENTE" ENABLE ROW LEVEL SECURITY;
