CREATE TABLE IF NOT EXISTS "DB029_LAN_ATENDIMENTO" (
  "000_Empresa" text,
  "001_CONCRETIZADO" text,
  "002_ATENDENTE" text,
  "003_DOC_FISCAL" text,
  "004_TIPO_FISCAL" text,
  "005_VENDEDOR" text,
  "006_TIPO-VENDA" text,
  "007_TOTAL_CUSTO_V+B" text,
  "008_TOTAL_BRUTO" text,
  "009_TOTAL_TAXAS" text,
  "010_DOC-FILE-URL" text,
  "011_ASS-CAMINHO-URL" text,
  "012_NF-Codigo-ENT" text,
  "013_NF-Codigo-SAI" text,
  "014_ASS-ASSINADO" text,
  "015_LINK-DOC-ASSINADO" text,
  "016_ENVIOU-DOC" text,
  "017_DOC-CRIADO" text,
  "018_FOLDER-STRUCT" text,
  "019_Chave" text,
  "020_URL_DANFE_FULL" text,
  "021_URL_DANFE_SIMPLES" text,
  "022_URL_XML" text,
  "023_UUID" text,
  "024_CIDADE-TXT" text,
  "025_ESTADO-TXT" text,
  "026_ATE-REFERENCIA" text,
  "027_POSSUI-ANEXO" text,
  "028_CANCELADO POR" text,
  "029_DATA_CANCELAMENTO" text,
  "030_MOTIVO_CANCELAMENTO" text,
  "031_AlteraTaxaAutorizado" text,
  "032_Termos-selecionados" text,
  "033_CLI-CPF" text,
  "034_CLI-NOME" text,
  "035_COD_ATENDIMENTO" text,
  "036_BRI_CUSTO-TOTAL" text,
  "037_BRI_PRODUTOS" text,
  "038_CLI-INFORMACOES" text,
  "039_CLI_INTENCAO" text,
  "040_COMO-CONHECEU" text,
  "041_DATA_VENDA" text,
  "042_END_BAIRRO" text,
  "043_END_CEP" text,
  "044_END_CIDADE" text,
  "045_END_ENDERECO" text,
  "046_END_ESTADO" text,
  "047_END_IBGE" text,
  "048_END_NUMERO" text,
  "049_FISCAL_PAGAMENTO" text,
  "050_LANCA-ATIVO" text,
  "051_LANCA-ESTOQUE" text,
  "052_LUCRO_BRUTO" text,
  "053_LUCRO_OPERACIONAL" text,
  "054_NF-COD_INTERNO" text,
  "055_OBS_INTERNO" text,
  "056_OBS_NA-NOTA" text,
  "057_PAGTO_CARTAO" text,
  "058_PAGTO_DESC-TOTAL" text,
  "059_PAGTO_DINHEIRO" text,
  "060_PAGTO_PIX" text,
  "061_PAGTO_TED" text,
  "062_STATUS" text,
  "063_TOTAL_CUSTO_V+B+TAXAS" text,
  "064_TOTAL_LIQUIDO" text,
  "065_TRO_CUSTO-TOTAL" text,
  "066_TRO_PRODUTOS" text,
  "067_VALOR_FRETE" text,
  "068_VEN_CUSTO-TOTAL" text,
  "069_VEN_PRODUTOS" text,
  "070_DESC ADICIONAL" text,
  "071_DESCONTO-PRODUTO" text,
  "072_DEVOLVIDO-VENDA" text,
  "073_Estilo_Saida" text,
  "074_MenuEntradaInfo" text,
  "075_son" text,
  "076_TXT_ESTADOS" text,
  "077_TXT_INTENCAO" text,
  "078_ID-UNICO" text,
  "079_z_CAP_CAR_Pagamento" text,
  "080_z_CAP_Custos" text,
  "081_z_CAR_Pagamento" text,
  "082_CRIADO_POR" text,
  "083_TipoInteracao" text,
  "084_COD_GARANTIA" text,
  "085_COD_GARANTIA TXT" text,
  "086_desc_acres-aprovado-por" text,
  "Creation Date" text,
  "Modified Date" text,
  "Slug" text,
  "Creator" text,
  "unique_id" text NOT NULL,
  "uuid" uuid NOT NULL DEFAULT gen_random_uuid(),
  CONSTRAINT "DB029_LAN_ATENDIMENTO_pkey" PRIMARY KEY ("unique_id", "uuid")
);
ALTER TABLE "DB029_LAN_ATENDIMENTO" ENABLE ROW LEVEL SECURITY;
