CREATE TABLE IF NOT EXISTS "DB032_LAN_GARANTIA" (
  "000_Empresa" text,
  "001_Ativo" text,
  "002_Cod Garantia" text,
  "003_Status" text,
  "004_Dados Cliente" text,
  "005_Nome Cliente" text,
  "006_CPF/CNPJ" text,
  "007_Atendente" text,
  "008_Responsável" text,
  "009_Data Garantia" text,
  "010_Tipo Garantia" text,
  "011_Tipo Garantia OS" text,
  "012_Atendimento Origem" text,
  "013_Atendimento Origem TXT" text,
  "014_Ordem de serviço Origem" text,
  "015_Ordem de serviço Origem TXT" text,
  "016_Cliente antigo" text,
  "017_Avarias" text,
  "018_Custo Produto Problema" text,
  "019_Custo Produto Problema (Lista)" text,
  "020_Preco Preoduto Problema (Lista)" text,
  "021_Preco Produto Problema" text,
  "022_Produto Ordem de serviço Problema" text,
  "023_Produto Ordem de serviço Problema TXT" text,
  "024_Produto Problema" text,
  "025_Produto Problema (Lista)" text,
  "026_Produto Problema Original" text,
  "027_Produto Problema Original (Lista)" text,
  "028_Produto Problema Original TXT" text,
  "029_Produto Problema TXT" text,
  "030_Origem" text,
  "031_Custo Produto Inicial Vendido" text,
  "032_Custo Produto Inicial Vendido (Lista)" text,
  "033_Custo Produto Vendido" text,
  "034_Custo Produto Vendido (Lista)" text,
  "035_Preco Produto Vendido" text,
  "036_Preco Produto Vendido (Lista)" text,
  "037_Produto Vendido" text,
  "038_Produto Vendido (Lista)" text,
  "039_Atendimento Garantia" text,
  "040_Atendimento Garantia TXT" text,
  "041_OS Garantia" text,
  "042_OS Garantia TXT" text,
  "Creation Date" text,
  "Modified Date" text,
  "Slug" text,
  "Creator" text,
  "unique_id" text NOT NULL,
  CONSTRAINT "DB032_LAN-GARANTIAS_pkey" PRIMARY KEY ("unique_id")
);
ALTER TABLE "DB032_LAN_GARANTIA" ENABLE ROW LEVEL SECURITY;
