CREATE TABLE IF NOT EXISTS "DB034_LAN_INICIANTE_ESTOQ" (
  "000_Empresa" text,
  "001_INI_EST_ATE_Cod_Lancamento" text,
  "002_INI_EST_Bateria" text,
  "003_INI_EST_Categoria" text,
  "004_INI_EST_Cor" text,
  "005_INI_EST_CPF" text,
  "006_INI_EST_DescontoDado" text,
  "007_INI_EST_Forma" text,
  "008_INI_EST_IMEI" text,
  "009_INI_EST_Memoria" text,
  "010_INI_EST_NomeCliente" text,
  "011_INI_EST_NumSerie" text,
  "012_INI_EST_Parcela" text,
  "013_INI_EST_Produto" text,
  "014_INI_EST_ProdutoConcatenado" text,
  "015_INI_EST_TipoLancamento" text,
  "016_INI_EST_TRO_ValorProposta" text,
  "017_INI_EST_Valor" text,
  "018_INI_EST_VEN_ValorVenda" text,
  "019_COD_INTERNO_LOJA" text,
  "020_EST_EntradaAtiva" text,
  "021_EST_VendaTotal" text,
  "022_Status" text,
  "023_Vendedor" text,
  "024_TXT_MEMORIA" text,
  "025_ID-UNICO" text,
  "026_Informacao_Temp" text,
  "Creation Date" text,
  "Modified Date" text,
  "Slug" text,
  "Creator" text,
  "unique_id" text NOT NULL,
  CONSTRAINT "DB034_LAN-INICIANTE-ESTOQS_pkey" PRIMARY KEY ("unique_id")
);
ALTER TABLE "DB034_LAN_INICIANTE_ESTOQ" ENABLE ROW LEVEL SECURITY;
