CREATE TABLE IF NOT EXISTS "DB041_LAN_SUPORTE" (
  "000_EMPRESA-TICKET]" text, "001_COD-TICKET]" text, "002_QUAL-MODULO]" text, "003_NIVEL-HIERARQ]" text, "004_DESCRICAO-TICKET]" text, "005_STATUS]" text, "006_NOME-USUARIO]" text, "007_CONTATO]" text, "008_ABERTO-POR]" text, "009_TIPO-SOLICITACAO]" text, "010_COMENTARIOS-TICKET]" text, "011_PRIORIDADE]" text, "012_FINALIZADO-SIM-NAO]" text, "013_FINALIZADO-POR]" text, "014_DATA-ABERTURA]" text, "015_DATA-FECHAMENTO]" text,
  "Creation Date" text, "Modified Date" text, "Slug" text, "Creator" text,
  "unique_id" text NOT NULL,
  CONSTRAINT "DB041_LAN-SUPORTES_pkey" PRIMARY KEY ("unique_id")
);
ALTER TABLE "DB041_LAN_SUPORTE" ENABLE ROW LEVEL SECURITY;
