CREATE TABLE IF NOT EXISTS "DB062_PROD_PRODUTO" (
    "000_Empresa" text,
    "001_ATIVO" text,
    "002_CAD_Preço_Varejo" text,
    "003_CAD_Preço_Atacado" text,
    "004_ACESS_CustoTotal" text,
    "005_ACESS_VendaTotal" text,
    "006_CAD_CustoMedio" text,
    "007_CAD_Est_Max" text,
    "008_CAD_Est_Min" text,
    "009_CAD_NomeConcatenado" text,
    "010_CAD_NomeProduto" text,
    "011_CAD_Servico_Avaria" text,
    "012_CAD_SKU" text,
    "013_CAD_TRO_Max" text,
    "014_CAD_TRO_Min" text,
    "015_CAD_Categoria" text,
    "016_CAD_Especificacoes" text,
    "017_CAD_Grupo" text,
    "018_CAD_Marca" text,
    "019_CAD_Memoria" text,
    "020_CAD_Memória_PC" text,
    "021_CAD_Subtipo" text,
    "022_CAD_TipoDeProdutoOS" text,
    "023_Saldo_de_estoque" text,
    "024_Custo_Externa" text,
    "025_Custo_Interna" text,
    "026_PrecoAjustado" text,
    "027_CODIGO-ASSOCIADO" text,
    "028_NF-Saldo Fiscal" text,
    "029_EMP_SALDO_FISCAL" text,
    "030_Remover" text,
    "031_TXT_ESPECIFICACOES" text,
    "032_TXT_MEMORIA" text,
    "033_TXT_SUBTIPO_PRODUTO" text,
    "034_TXT_TIPO_PRODUTO" text,
    "035_TXT_MEMORIA PC [OS] ESPECIFICACOES" text,
    "036_ID-UNICO" text,
    "037_Estoque-acessorio" text,
    "Creation Date" text,
    "Modified Date" text,
    "Slug" text,
    "Creator" text,
    "unique_id" text NOT NULL,
    CONSTRAINT "DB062_PROD_PRODUTOS_pkey" PRIMARY KEY ("unique_id")
);

ALTER TABLE "DB062_PROD_PRODUTO" ENABLE ROW LEVEL SECURITY;
