CREATE TABLE IF NOT EXISTS "DB072_RF_ICMS_INFO" (
    "000_Empresa" text,
    "001_ID-INTERNO" text,
    "002_TIPO_PESSOA" text,
    "003_CENARIO_FISCAL" text,
    "004_SIT_TRIBUT" text,
    "005_CFOP" bigint,
    "006_TIPO_TRIBUTACAO" text,
    "007_ALIQ_MVA" text,
    "008_ALIQ_ICMS" text,
    "009_ALIQ_ICMS-ST" text,
    "010_ALIQ_FCP" text,
    "011_ALIQ_FCP-ST" text,
    "012_ALIQ_BENEFICIO" text,
    "013_ALIQUOTA-ICMS" text,
    "014_ALIQUOTA-BC-ICMS" text,
    "015_ALIQUOTA-BC-ICMS-ST" text,
    "016_ALIQUOTA-EFET-BC-ICMS" bigint,
    "017_ALIQUOTA-EFET-BC-ICMS-ST" text,
    "018_IPI" text,
    "019_BC_ST-Retido" text,
    "020_Aliq_ST-Retido" text,
    "021_Valor_ST-Retido" text,
    "022_Valor_ICMS-Substituto" text,
    "023_Valor_FCP-Retido" text,
    "024_Aliq_FCP-Retido" text,
    "025_Aliq_BC_Efetivo" text,
    "026_Aliq_ICMS_Efet" text,
    "027_Aliq_ICMS-Diferim" text,
    "028_Aliq_ICMS-ST-DiferimFCP" text,
    "029_Motiv_Deson-ICMS" text,
    "030_Motiv_Deson-ICMS-ST" text,
    "031_WMBR] - Cenario" text,
    "032_WMBR] - COFINS-Situacoes" text,
    "033_WMBR] - Pessoa" text,
    "034_WMBR] - Tipo_de_tributacao" text,
    "035_ICMS [WMBR] - Motivo" text,
    "036_ICMS-ST [WMBR] - Motivo" text,
    "037_ID-UNICO" text,
    "Creation Date" text,
    "Modified Date" text,
    "Slug" text,
    "Creator" text,
    "unique_id" text NOT NULL,
    CONSTRAINT "DB072_RF_ICMS_INFO_pkey" PRIMARY KEY ("unique_id")
);

ALTER TABLE "DB072_RF_ICMS_INFO" ENABLE ROW LEVEL SECURITY;
