CREATE TABLE IF NOT EXISTS "DB073_RF_INFO_FISCAL" (
    "000_Empresa" text,
    "001_ATIVO" text,
    "002_RF - CERT-VALIDO" text,
    "003_RF - CIDADE_IBGE" bigint,
    "004_RF - CNAE_PRINCIPAL" text,
    "005_RF - CNAE_PRINCIPAL_DESCRICAO" text,
    "006_RF - CNPJ" text,
    "007_RF - END_BAIRRO" text,
    "008_RF - END_CEP" text,
    "009_RF - END_CIDADE" text,
    "010_RF - END_CONCATENADO" text,
    "011_RF - END_ENDERECO" text,
    "012_RF - END_ESTADO" text,
    "013_RF - END_NUMERO" text,
    "014_RF - END_TIPO" text,
    "015_RF - Estado IE" text,
    "016_RF - INICIO_ATIVIDADES" text,
    "017_RF - NAT_JURIDICA" text,
    "018_RF - NOME_FANTASIA" text,
    "019_RF - OPTANTE_MEI" text,
    "020_RF - OPTANTE_SIMPLES" text,
    "021_RF - PORTE" text,
    "022_RF - RAZAO_SOCIAL" text,
    "023_RF - REGIME_TRIBUTARIO" text,
    "024_RF - SITUACAO" text,
    "025_RF - TELEFONE_01" text,
    "026_RF - IE" text,
    "027_RF - IM" text,
    "028_Cert-Base64" text,
    "029_Cert-Expira" text,
    "030_Cert-Senha" text,
    "031_NFE-SERIE" bigint,
    "032_NFE-ATUAL-NOTA" bigint,
    "033_SERIE-NFCE" text,
    "034_NFCE-ATUAL-NOTA" text,
    "035_NFCE-ID-CSC" text,
    "036_NFCE-CODIGO-CSC" text,
    "037_NFSE-SERIE" text,
    "038_NFSE-ATUAL-RPS" text,
    "039_NFSE-LOGIN" text,
    "040_NFSE-SENHA" text,
    "041_CompanyId" text,
    "042_NFE-INFO-FISCO" text,
    "043_NFSE_INFO_FISCAL" text,
    "044_UNIDADE EMPRESA" text,
    "045_WM - EMP_UUID" text,
    "046_WMBR - AccessToken" text,
    "047_WMBR - AccessTokenSecret" text,
    "048_WMBR - BearerAccessToken" text,
    "049_WMBR - ClaImp - Entrada" text,
    "050_WMBR - ClaImp - Saida" text,
    "051_WMBR - ConsumerKey" text,
    "052_WMBR - ConsumerSecret" text,
    "053_WMBR - ID" text,
    "054_RF - TIPO_TRIBUTACAO" text,
    "055_TXT_ESTADOS" text,
    "056_TXT_REGIME_TRIBUTARIO" text,
    "057_WMBR] Tipo_de_tributacao" text,
    "058_ID-UNICO" text,
    "059_IBS/CBS-RemoverObrigatoriedade" text,
    "Creation Date" text,
    "Modified Date" text,
    "Slug" text,
    "Creator" text,
    "unique_id" text NOT NULL,
    CONSTRAINT "DB073_RF_INFO_FISCAL_pkey" PRIMARY KEY ("unique_id")
);

ALTER TABLE "DB073_RF_INFO_FISCAL" ENABLE ROW LEVEL SECURITY;
