CREATE TABLE IF NOT EXISTS "DB082_TREL_TAREFA_MANUT" (
    "000_Empresa" text,
    "[00] - NOME" text,
    "[00] - PRIORIDADE" text,
    "[00] - PROJETO" text,
    "[00] - RESPONSAVEL" text,
    "[00] - RESUMO" text,
    "[00] - STATUS" text,
    "[01] - APROVADO?" text,
    "[01] - CHECKLIST" text,
    "[02] - DESCRICAO" text,
    "[03] - COMENTARIOS" text,
    "[04] - LINK" text,
    "[50] - COD_OS_TASK" text,
    "[50] - COD_SEQ" text,
    "[50] - COD_TASK" text,
    "[51] - CPF_CLIENTE" text,
    "[51] - DADOS_CLIENTE" text,
    "[51] - NOME_CLIENTE" text,
    "[52] - OS_CANCELADO POR" text,
    "[52] - OS_DATA_CANCELAMENTO" text,
    "[52] - OS_MOTIVO_CANCELAMENTO" text,
    "[52] - STATUS_OS" text,
    "[53] - ATIVO" text,
    "[54] - DATA_TASK" text,
    "[55] - RESPONSAVEL" text,
    "[56] - CRIADO POR" text,
    "[57] - PROD_CLIENTE" text,
    "[60] - MEMORIA_ESPECIFICACAO" text,
    "[61] - BATERIA" text,
    "[62] - COR" text,
    "[63] - IMEI" text,
    "[64] - NUM_SERIE" text,
    "[65] - ESTOQUE_LOCAL" text,
    "[66] - CHECKLIST_ORIGEM" text,
    "[67] - CHECK_PROBLEMAS" text,
    "[67] - CHECK_PROBLEMAS_INICIAL" text,
    "[68] - APARELHO_TEM_CHIP" text,
    "[68] - ID_APPLE" text,
    "[68] - MARCAS_DE_USO" text,
    "[68] - MOTIVO_ASSISTENCIA_ANTERIOR" text,
    "[68] - OBSERVACOES_GERAIS" text,
    "[68] - PASSOU_ASSISTENCIA_ANTERIOR" text,
    "[68] - PASSOU_GARANTIA_APPLE" text,
    "[68] - SENHA_APARELHO_CLIENTE" text,
    "[68] - SENHA_ICLOUD" text,
    "[68] - TEMPO_USO" text,
    "[70] - PRECO-ESTIMADO" text,
    "[71] - CUSTO_MAODEOBRA_SERVICO" text,
    "[71] - E-MAIL_CLIENTE" text,
    "[71] - LISTA_PRECOS_SERVICOS" text,
    "[71] - LISTA_SERVICO" text,
    "[71] - SERVIÇOS" text,
    "[71] - TELEFONE_CLIENTE" text,
    "[72] - PRAZO_ORCAMENTO" text,
    "[72] - SALDO_DEVEDOR" text,
    "[72] - STATUS_PAGAMENTO" text,
    "[72] - VALIDADE_ORCAMENTO" text,
    "[73] - ORÇAMENTO_INICIAL" text,
    "[73] - Tipo_Assistencia" text,
    "[74] - ChipDevolvido" text,
    "[74] - OBS_PAGTO_CLIENTE" text,
    "[74] - OBS_PAGTO_LOJA" text,
    "[74] - Pagto_Frete" text,
    "[74] - PrazoEstimado" text,
    "[74] - TermoGarantia" text,
    "[75] - NOTA_FISCAL" text,
    "[80] - DOC-FILE-URL-RECIBO" text,
    "[81] - ASS-CAMINHO-URL-RECIBO" text,
    "[82] - ENVIOU-DOC-RECIBO" text,
    "[83] - DOC-CRIADO-RECIBO" text,
    "[84] - FOLDER-STRUCT" text,
    "[85] - DOC-FILE-URL-FINAL" text,
    "[86] - ASS-CAMINHO-URL-FINAL" text,
    "[87] - ENVIOU-DOC-FINAL" text,
    "[88] - DOC-CRIADO-FINAL" text,
    "[99] - CHECKLIST POSTERIOR" text,
    "[99] - CHECKLIST_ORIGEM_POSTERIOR" text,
    "[99] - CHECKLIST_PERGUNTADO" text,
    "[99] - CHECKLIST_POSTERIOR_LISTA" text,
    "[99] - Custo_Pecas" text,
    "[99] - Desligado" text,
    "[99] - Finalizado em" text,
    "[99] - Finalizado por" text,
    "[99] - Lista Custo_Pecas_CI" text,
    "[99] - Lista Custo_Peças_SI" text,
    "[99] - Lista_Pecas_CI_Utilizadas" text,
    "[99] - Lista_Pecas_SI_Utilizadas" text,
    "[99] - Local Manutencao" text,
    "[99] - LOCAL-INT-EXT" text,
    "[99] - LOCAL-REPARO" text,
    "[99] - Pecas_CI_Utilizadas" text,
    "[99] - Pecas_SI_Utilizadas" text,
    "[99] - QR-CODE" text,
    "ASSINADO-FINAL" text,
    "ASSINADO-RECIBO" text,
    "POSSUI-ANEXO" text,
    "Z - Custo_MaoDeObra" text,
    "Z - Lista_CAP-CAR" text,
    "Z - LucroBrutoOS" text,
    "Z - LucroOS" text,
    "Z - PAGTO_Boleto" text,
    "Z - PAGTO_Cartao" text,
    "Z - PAGTO_Dinheiro" text,
    "Z - PAGTO_PIX" text,
    "Z - PAGTO_TED" text,
    "Z - Taxas" text,
    "Z - TotalCustoOS" text,
    "Z - TotalCustoOS_SEMTAXAS" text,
    "Z - TotalPagoCliente" text,
    "Z - ValorEstimadoFinal" text,
    "ZZZ - Garantia" text,
    "Creation Date" text,
    "Modified Date" text,
    "Slug" text,
    "Creator" text,
    "unique_id" text NOT NULL,
    CONSTRAINT "DB082_TREL_TAREFA_MANUT_pkey" PRIMARY KEY ("unique_id")
);

ALTER TABLE "DB082_TREL_TAREFA_MANUT" ENABLE ROW LEVEL SECURITY;
