CREATE TABLE IF NOT EXISTS "DB113_UTILIZACAO_SUBMODULOS" (
  "000_Empresa" text,
  "[100] - CAD-Produtos" bigint,
  "[101] - CAD-Grupos" bigint,
  "[102] - CAD-Marcas" bigint,
  "[103] - CAD-Avarias" text,
  "[104] - CAD-Cores" text,
  "[105] - CAD-Categorias" bigint,
  "[106] - CAD-Local" bigint,
  "[107] - CAD-Cliente" bigint,
  "[108] - CAD-Fornecedor" text,
  "[201] - OPS-Atendimento" bigint,
  "[202] - OPS-Estoque" bigint,
  "[203] - OPS-SimularVenda" bigint,
  "[204] - OPS-SimularTaxas" text,
  "[205] - OPS-Comodato" text,
  "[206] - OPS-PreVenda" bigint,
  "[207] - OPS-Garantia" bigint,
  "[208] - OPS-EstoqueInutilizado" text,
  "[301] - FIN-ContaReceber" bigint,
  "[302] - FIN-ContaPagar" bigint,
  "[303] - FIN-Compras" bigint,
  "[304] - FIN-DRE" bigint,
  "[401] - REL-Cadastros" bigint,
  "[402] - REL-Vendas" bigint,
  "[403] - REL-Estoque" bigint,
  "[404] - REL-Financeiro" bigint,
  "[405] - REL-TrafegoPago" bigint,
  "[406] - REL-Gerencial" bigint,
  "[407] - REL-Fiscal" bigint,
  "[408] - REL-Assistencia" text,
  "[501] - UTI-TabelaVenda" bigint,
  "[502] - UTI-TabelaTroca" bigint,
  "[503] - UTI-TabelaAvarias" text,
  "[504] - UTI-TabelaServicos" text,
  "[505] - UTI-AjusteEstoque" bigint,
  "[506] - UTI-Transferencia" text,
  "[507] - UTI-EstoqueCompartilhado" text,
  "[508] - UTI-Etiquetas" text,
  "[601] - FIS-Instrucoes" text,
  "[602] - FIS-NotaEntrada" text,
  "[603] - FIS-NotaSaida" text,
  "[604] - FIS-NotaCanceladas" bigint,
  "[605] - FIS-EstoqueFiscal" text,
  "[606] - FIS-RegrasFiscais" text,
  "[607] - FIS-NCM-CEST" text,
  "[608] - FIS-Configuracoes" bigint,
  "[609] - FIS-NotaServico" text,
  "[610] - FIS-MonitorFiscal" bigint,
  "[701] - ASS-OrdemServico" text,
  "[702] - ASS-EstoqueManutencao" text,
  "[703] - ASS-EstoquePecas" bigint,
  "[704] - ASS-EsteiraManutencao" text,
  "[705] - ASS-Servicos" text,
  "[706] - ASS-CheckList" text,
  "[707] - AST-Garantia" text,
  "[801] - ADI-TrafegoPago" text,
  "[802] - ADI-CRM" text,
  "[803] - ADI-AgendaComercial" text,
  "[804] - ADI-Metas" text,
  "[805] - ADI-Marketplace" text,
  "[806] - ADI-ChaveAPI" text,
  "[807] - ADI-Patrimonio" text,
  "[808] - ADI-Devocional" text,
  "[809] - ADI-AuditoriaInterna" bigint,
  "[901] - CON-Gerais" text,
  "[902] - CON-TrocaUsuario" bigint,
  "[903] - CON-TrocaLoja" text,
  "[904] - CON-DarSugestao" text,
  "Creation Date" text,
  "Modified Date" text,
  "Slug" text,
  "Creator" text,
  "unique_id" text NOT NULL,
  CONSTRAINT "DB113_UTILIZACAO_SUBMODULOS_pkey" PRIMARY KEY ("unique_id")
);

ALTER TABLE "DB113_UTILIZACAO_SUBMODULOS" ENABLE ROW LEVEL SECURITY;
