CREATE TABLE IF NOT EXISTS "DB999_VERIF_CONTAS_RECEB" (
  "000_Empresa" text,
  "0ATE_Cod__01" text,
  "0Nome_Cliente__02" text,
  "ATE_Cod__03" text,
  "CAR_Cod__04" text,
  "Taxas_Lojista__06" text,
  "ValorComAcrescimo__07" text,
  "ValorSemAcrescimo__08" text,
  "Z-OPT [OS] BANDEIRAS" text,
  "Z-OPT [OS] FORMA_PAGTO" text,
  "Z-UNIQUE - ID-UNICO" text,
  "ZAtivo__09" text,
  "zBandeira__10" text,
  "ZCAR_Cod__11" text,
  "ZContaReceb__12" text,
  "ZDataComp__13" text,
  "zDesconto__14" text,
  "zForma__15" text,
  "zMaquina__16" text,
  "zParcela__17" text,
  "zSituação__18" text,
  "zValor__19" text,
  "zValorComTaxa__20" text,
  "ZValorNegativo__21" text,
  "ZValorPositivoPAC__22" text,
  "zValorReceber__23" text,
  "zzBotaoSemJuros__24" text,
  "Creation Date" text,
  "Modified Date" text,
  "Slug" text,
  "Creator" text,
  "unique_id" text NOT NULL,
  CONSTRAINT "DB999_VERIF_CONTAS_RECEBS_pkey" PRIMARY KEY ("unique_id")
);

ALTER TABLE "DB999_VERIF_CONTAS_RECEB" ENABLE ROW LEVEL SECURITY;
