CREATE TABLE IF NOT EXISTS "User" (
  "001_EmpresaWeb" text,
  "002_EmpresaApp" text,
  "00_EMP_Vinculadas" text,
  "01 - ativo" text,
  "02 - nomeUsuario" text,
  "03 - sobrenomeUsuario" text,
  "04 - emailUsuario" text,
  "05 - perfilUsuario" text,
  "06 - filasUsuario" text,
  "07 - fotoUsuario" text,
  "08 - departamentoUsuario" text,
  "09 - instancias" text,
  "20 - FUNCAO_LOGADA" text,
  "21 - FUNCAO_VINCULADA" text,
  "50 - CRM-NOME_CHAT" text,
  "51 - CRM-DADOS_USER" text,
  "81 - ULTIMO_CHANGELOG" text,
  "82 - Acesso Master" text,
  "88 - AtualizaPag" text,
  "99_Dispositivos" text,
  "[TEMP] - Pesquisa CHURN" text,
  "basico_completo" text,
  "Como_conheceu" text,
  "CPF" text,
  "DATA NASCI" text,
  "INATIVO-Usuario_permissao" text,
  "Logo_empresa2" text,
  "LogoEmpresa" text,
  "nome" text,
  "NPS" text,
  "NPS-GERAL-RESPONDIDO" text,
  "Telefone" text,
  "telefone_mascarado" text,
  "telefone_whatsapp" text,
  "Token" text,
  "WhatsApp-Instancia" text,
  "Creation Date" text,
  "Modified Date" text,
  "Slug" text,
  "email" text,
  "null" text,
  "unique_id" text NOT NULL,
  CONSTRAINT "Users_pkey" PRIMARY KEY ("unique_id")
);

ALTER TABLE "User" ENABLE ROW LEVEL SECURITY;
