-- ============================================================================
-- LANCAMENTO ESTOQUE (DB031_LAN_ESTOQUE)
-- Tabela 1:1 com DB031 para migracao dos dados do Bubble.
-- Origem: output/lancamento_estoque.sql (bubble_supabase)
-- ============================================================================
create table lancamento_estoque (
  id bigint generated always as identity primary key,
  bubble_unique_id text unique,
  -- DB031 campos 1-96 na ordem original
  status text,
  cod_os text,
  est_sku text,
  ate_cod text,
  est_imei text,
  est_nome text,
  vendedor_id bigint references usuarios(id),
  atendente_id bigint references usuarios(id),
  data_movimentacao date,
  est_origem text,
  nome_cliente text,
  cancelado boolean default false,
  est_qtd numeric(12,2),
  est_num_serie text,
  txt_memoria text,
  informacao_temp boolean default true,
  nf_cor text,
  nf_ncm text,
  est_bateria numeric(12,2),
  est_cor_id bigint references cores(id),
  seq_xml text,
  nf_cest text,
  bri_desconto numeric(12,2),
  est_cod_interno text,
  est_custo_proposta_atualizado numeric(12,2),
  com_cod text,
  nf_categ text,
  menu_entrada_info text,
  transferencia boolean default false,
  cod_interno_loja text,
  com_custo_total numeric(12,2),
  est_preco_venda numeric(12,2),
  est_reservado_por_id bigint references usuarios(id),
  est_venda_total numeric(12,2),
  est_marca_id bigint references marcas(id),
  est_qtd_negativa numeric(12,2),
  percentual numeric(12,2),
  garantia_flag boolean,
  nf_subcateg text,
  est_cod_lancamento text,
  est_desconto_total_dado numeric(12,2),
  est_grupo_id bigint references grupos(id),
  est_nome_prod_concat text,
  est_tipo_lancamento text,
  txt_estoques text,
  est_acrescimo_dado numeric(12,2),
  est_entrada_ativa boolean default false,
  est_identificado boolean,
  fotos_produto text[],
  intencao text,
  id_unico text,
  ent_fiscal boolean default false,
  empresa_id bigint references empresas(id),
  est_categoria_id bigint references categorias(id),
  est_lucro_unitario numeric(12,2),
  sai_fiscal boolean default false,
  est_estoque text,
  est_memoria text,
  assis_cliente boolean,
  info_inutilizacao text,
  nf_id_prod_unif text,
  nf_custo_unit numeric(12,2),
  cod_os_tarefa_id bigint references ordens_servico(id),
  est_nome_origem_cli_outro text,
  proporcao_desc_extra numeric(12,2),
  produto_id bigint references produtos(id),
  txt_tipo_produto text,
  nf_prod_custo_total numeric(12,2),
  est_avarias_ids jsonb,
  est_avarias_desconto_total numeric(12,2),
  est_custo_proposta_inicial numeric(12,2),
  est_estoque_lo_id bigint references locais_estoque(id),
  origem_transferencia text,
  checklist_realizado boolean default false,
  lest_observacoes_adicionais text,
  est_desconto_no_produto numeric(12,2),
  desc_acres_aprovado_por_id bigint references usuarios(id),
  checklist_aprovado text[],
  nf_cod_id bigint references notas_fiscais(id),
  checklist_nao_aprovado text[],
  com_cod_lancamento_id bigint references compras(id),
  est_especificacao text,
  est_tipo_de_produto_os text,
  ate_cod_lancamento_id bigint references atendimentos(id),
  origem_cliente_id bigint references clientes(id),
  est_avarias_nome_ids jsonb,
  nome_origem_fornecedor_id bigint references fornecedores(id),
  xml_id_unico text,
  emp_cod_lanca_id bigint references emprestimos(id),
  regra_fiscal_id bigint references parametros_imposto(id),
  nf_emissor_id bigint references info_fiscal(id),
  transferencia_id bigint references transferencias(id),
  info_fiscal_estoque_id bigint,
  estoque_referenciado_id bigint references lancamento_estoque(id),
  checklist_id bigint references checklist_avaliacao(id),
  xml_id text
);

create index idx_le_bubble_unique_id on lancamento_estoque(bubble_unique_id);
create index idx_le_empresa on lancamento_estoque(empresa_id);
create index idx_le_produto on lancamento_estoque(produto_id);
create index idx_le_data_movimentacao on lancamento_estoque(data_movimentacao);

comment on table lancamento_estoque is 'Tabela 1:1 com DB031_LAN_ESTOQUE (96 campos). Migracao dos dados do Bubble.';

alter table lancamento_estoque enable row level security;
